# Generated by Django 3.2.6 on 2021-09-04 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0012_alter_project_wiki'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='list',
            new_name='list_id',
        ),
        migrations.RenameField(
            model_name='list',
            old_name='project',
            new_name='project_id',
        ),
    ]
