# Generated by Django 3.2.6 on 2021-09-04 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0014_auto_20210904_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default='2021/09/05'),
        ),
        migrations.AlterField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default='2021/09/05'),
        ),
        migrations.AlterField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(default='2021/09/05'),
        ),
        migrations.AlterField(
            model_name='list',
            name='start_date',
            field=models.DateTimeField(default='2021/09/05'),
        ),
    ]
