# Generated by Django 3.2.6 on 2021-09-05 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0019_auto_20210905_0606'),
    ]

    operations = [
    ]
