# Generated by Django 3.2.6 on 2021-09-07 08:09

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0027_auto_20210907_0730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='wiki',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
