# Generated by Django 3.2.6 on 2021-09-09 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0029_auto_20210908_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoflist',
            name='assigned_member',
            field=models.ManyToManyField(blank=True, to='todo.User'),
        ),
    ]
