# Generated by Django 3.2.6 on 2021-09-09 05:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_alter_listofproject_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoflist',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to=settings.AUTH_USER_MODEL),
        ),
    ]
