# Generated by Django 3.2.6 on 2021-09-09 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_project_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardoflist',
            name='creator',
            field=models.EmailField(max_length=254),
        ),
    ]
