# Generated by Django 3.2.6 on 2021-10-01 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20211001_0944'),
    ]

    operations = [
    ]
