# Generated by Django 3.2.6 on 2021-09-02 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('projtitle', models.CharField(max_length=50)),
                ('wiki', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='projectMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment', models.BigIntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='regestereduser',
            name='roles',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listtitle', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.project')),
            ],
        ),
        migrations.CreateModel(
            name='card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardtitle', models.CharField(max_length=50)),
                ('desc', models.CharField(max_length=500)),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.list')),
            ],
        ),
        migrations.CreateModel(
            name='assignees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.card')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.regestereduser')),
            ],
        ),
    ]
