# Generated by Django 3.2.6 on 2021-10-10 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='projtitle',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
