# Generated by Django 3.2.6 on 2021-09-02 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210902_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='regestereduser',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='regestereduser',
            name='is_superuser',
        ),
    ]
