# Generated by Django 3.2.6 on 2021-09-02 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_regestereduser_isactive'),
    ]

    operations = [
        migrations.AddField(
            model_name='regestereduser',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AddField(
            model_name='regestereduser',
            name='password',
            field=models.CharField(default='name', max_length=128, verbose_name='password'),
            preserve_default=False,
        ),
    ]
