# Generated by Django 3.2.6 on 2021-09-04 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0010_auto_20210904_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignees',
            name='card',
        ),
        migrations.RemoveField(
            model_name='assignees',
            name='enrollment',
        ),
        migrations.DeleteModel(
            name='projectMember',
        ),
        migrations.DeleteModel(
            name='assignees',
        ),
    ]
