# Generated by Django 3.2.6 on 2021-09-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0013_auto_20210904_2059'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='due_date',
            field=models.DateTimeField(default='05/09/2021'),
        ),
        migrations.AddField(
            model_name='card',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='card',
            name='start_date',
            field=models.DateTimeField(default='05/09/2021'),
        ),
        migrations.AddField(
            model_name='list',
            name='due_date',
            field=models.DateTimeField(default='05/09/2021'),
        ),
        migrations.AddField(
            model_name='list',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='start_date',
            field=models.DateTimeField(default='05/09/2021'),
        ),
    ]
