# Generated by Django 3.2.6 on 2021-09-04 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0015_auto_20210904_2232'),
    ]

    operations = [
    ]
