# Generated by Django 3.2.6 on 2021-09-05 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0020_auto_20210905_0608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='assigned_member',
            field=models.ManyToManyField(to='todo.User'),
        ),
        migrations.AlterField(
            model_name='project',
            name='member',
            field=models.ManyToManyField(to='todo.User'),
        ),
    ]
