# Generated by Django 3.2.6 on 2021-09-05 06:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0021_auto_20210905_0610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_completed',
        ),
        migrations.RemoveField(
            model_name='list',
            name='is_completed',
        ),
    ]
