# Generated by Django 3.2.6 on 2021-09-02 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_auto_20210902_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='regestereduser',
            name='isactive',
            field=models.BooleanField(default=True),
        ),
    ]
