# Generated by Django 3.2.6 on 2021-09-05 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0018_auto_20210904_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='card',
            name='start_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='due_date',
        ),
        migrations.RemoveField(
            model_name='list',
            name='start_date',
        ),
    ]
