# Generated by Django 3.2.6 on 2021-09-05 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0022_auto_20210905_0617'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='list',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
