# Generated by Django 3.2.6 on 2021-09-07 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0026_project_creator'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='card',
            new_name='cardOfList',
        ),
        migrations.RenameModel(
            old_name='list',
            new_name='listOfProject',
        ),
    ]
