# Generated by Django 3.2.6 on 2021-09-08 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0028_alter_project_wiki'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardoflist',
            name='creator',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listofproject',
            name='creator',
            field=models.EmailField(default='admin@gmail.com', max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cardoflist',
            name='assigned_member',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='creator',
            field=models.EmailField(max_length=254),
        ),
    ]
